version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Asia/Dubai
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume2/docker/portainer:/data
    ports:
      - 9000:9000
